name: 'modeling'
version: '1.0.0'
config-version: 2

profile: 'modeling'

model-paths: ["models"]

clean-targets:    # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  modeling:
    staging:
      +materialized: table

vars:
  conditional_format: ''
  date_format: ''
